swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  # Récupérer toutes les transactions du mois en cours, groupées par compte
  /accounts/{accountId}/transactions:
    get:
      summary: Get transactions for the current month
      description: Retrieve all transactions of a bank account for the current month.
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: The bank account ID.
      responses:
        '200':
          description: List of transactions retrieved successfully.
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '401':
          description: User not logged in.
        '404':
          description: Account not found.

  # Voir les détails d’une transaction spécifique
  /transactions/{transactionId}/details:
    get:
      summary: Get transaction details
      description: Retrieve detailed information about a specific transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: Unique transaction ID.
      responses:
        '200':
          description: Transaction details retrieved successfully.
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: User not logged in.
        '404':
          description: Transaction not found.

  # Modifier une transaction (ajout/modif/suppression d'infos)
  /transactions/{transactionId}:
    put:
      summary: Update transaction details
      description: Modify details of a transaction (such as category, notes, or other metadata).
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: The unique ID of the transaction.
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: Transaction updated successfully.
        '400':
          description: Invalid data.
        '401':
          description: User not logged in.
        '404':
          description: Transaction not found.

# Définition des objets utilisés dans les réponses
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
      date:
        type: string
      amount:
        type: number
      type:
        type: string
        description: "credit or debit"
      category:
        type: string
      notes:
        type: string
      details:
        type: string
        description: Additional details about the transaction.

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
      details:
        type: string
        description: Additional details to modify.
